import time
import os
import sys
import json
import psutil
import ollama
from pathlib import Path # Adiciona caminhos do projeto
BASE_DIR = Path("c:/Users/Lucas Val rio/Desktop/MODELO GENIO LLM")
sys.path.append(str(BASE_DIR / "src" / "agentes" / "passivos" / "extratores")) # Importa o robusta do Soldado de Vis o SOTA
try: from extrator_imagem_soldado_SRC_GL import ExtratorImagem soldado_visao = ExtratorImagem() print("[OK] Soldado de vis o carregado com sucesso.")
except ImportError: soldado_visao = None print("[WARN] Soldado de vis o n o encontrado. Usando fallback direto (Ollama).") def testar_imagem(caminho_imagem, pergunta): """Executa o teste para uma imagem e pergunta.""" print(f"\n[SCAN] Testando imagem: {caminho_imagem.name}") print(f" Pergunta: {pergunta}") if soldado_visao: # Usa a interface SOTA v40.3 resultado = soldado_visao.executar({"caminho": str(caminho_imagem), "prompt": pergunta}) return resultado.get("texto", "Errorrr na extra o.") else: # Fallback direto via Ollama API with open(caminho_imagem, 'rb') as f: imagem_bytes = f.read() resposta_ollama = ollama.generate( model='qwen2-vl:7b', prompt=pergunta, images=[imagem_bytes] ) return resposta_ollama['response'] def medir_recursos(): """Retorna uso de VRAM (se dispon vel) e RAM.""" vram = None try: import subprocess result = subprocess.run( ['nvidia-smi', '--query-gpu=memory.used', '--format=csv,noheader,nounits'], capture_output=True, text=True, check=True ) vram = int(result.stdout.strip()) except: pass ram = psutil.virtual_memory().used / (1024**2) # MB return ram, vram def main(): imagens_dir = Path(__file__).parent / "imagens_teste" if not imagens_dir.exists(): print(f"[ERR] Pasta de imagens n o encontrada: {imagens_dir}") return testes = [ ("objetos.jpg", "Descreva os objetos na imagem e suas cores."), ("texto.png", "Leia o texto presente na imagem. O que est escrito no painel?"), ("contagem.jpg", "Quantas bolas verdes voc v no recipiente? Responda o n mero exato.") ] resultados = [] print("[BOOST] INICIANDO BENCHMARK MULTIMODAL SOTA v40.3...") for arquivo, pergunta in testes: caminho = imagens_dir / arquivo if not caminho.exists(): print(f"[WARN] Arquivo {arquivo} n o encontrado. Pule este teste.") continue ram_antes, vram_antes = medir_recursos() inicio = time.time() try: resposta = testar_imagem(caminho, pergunta) except Exception as e: resposta = f"ERRO: {str(e)}" fim = time.time() ram_depois, vram_depois = medir_recursos() resultado_metrizado = { "imagem": arquivo, "pergunta": pergunta, "resposta": resposta, "tempo_seg": round(fim - inicio, 2), "ram_delta_mb": round(ram_depois - ram_antes, 2), "vram_antes": vram_antes, "vram_depois": vram_depois, "vram_delta_mb": (vram_depois - vram_antes) if vram_antes and vram_depois else 0 } resultados.append(resultado_metrizado) print(f"[TIME] Tempo: {fim - inicio:.2f}s") print(f"[NOTE] Resposta: {resposta[:300]}...") # Salva relat rio em .panda/benchmarks/ os.makedirs(str(BASE_DIR / ".panda" / "benchmarks"), exist_ok=True) relatorio_path = BASE_DIR / ".panda" / "benchmarks" / "teste_visao_v40_3.json" with open(relatorio_path, "w", encoding="utf-8") as f: json.dump(resultados, f, indent=4, ensure_ascii=False) print(f"\n[OK] Teste conclu do com sucesso!") print(f"[LOC] Relat rio salvo em: {relatorio_path}") if __name__ == "__main__": main()
